services:
  - type: web
    name: sanctuary-api
    runtime: python
    buildCommand: pip install -r /backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: postgresql://neondb_owner:npg_jVTk7HLG9enX@ep-wild-rain-ao89sow0.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: CLIENT_ORIGIN
        sync: https://fintrack-flame-nine.vercel.app          # your Vercel frontend URL